import type { BookData } from "./types"

export const booksData: BookData[] = [
  {
    id: "x-101",
    title: "X 101",
    subtitle: "The Ultimate Guide to Posting",
    author: "Guillermo Rauch",
    publishedYear: 2025,
    pages: 186,
    description: [
      "Master the art of viral content creation on X with insider strategies from one of the platform's most successful creators. Learn the psychology behind engagement and the secrets to crafting posts that resonate.",
      "From understanding algorithms to building authentic connections, Rauch reveals the proven techniques that turn ordinary thoughts into extraordinary social media moments, colloquially known as bangers.",
    ],
    genres: ["Social Media", "Marketing", "Digital Strategy"],
    rating: 4.9,
    reviews: 15623,
    materialProps: {
      color: "#000000",
      metalness: 0.8,
      roughness: 0.2,
      emissive: "#000000",
      emissiveIntensity: 0,
      texture: null,
      offsetX: -0.02,
      offsetY: 0,
    },
    backgroundColor: "#FFFFFF",
    textColor: "black",
  },
  {
    id: "gewoon-beginnen-met-ai",
    title: "Gewoon Beginnen met AI+",
    subtitle: "Een gids voor elke ondernemer die wil starten met AI in zijn of haar bedrijf",
    author: "Colin Duivenvoorden",
    publishedYear: 2024,
    pages: 256,
    description: [
      "Elke ondernemer kan AI leren en gebruiken! Deze praktische gids laat zien hoe je als ondernemer kunt profiteren van kunstmatige intelligentie, zonder dat je een technische achtergrond nodig hebt.",
      "Van chatbots tot automatisering, van data-analyse tot klantservice - ontdek hoe AI jouw bedrijf kan transformeren. Met concrete voorbeelden en stap-voor-stap uitleg word je begeleid naar succesvolle AI-implementatie.",
    ],
    genres: ["Business", "AI", "Ondernemerschap", "Technologie"],
    rating: 4.8,
    reviews: 2847,
    materialProps: {
      color: "#22C55E",
      metalness: 0.3,
      roughness: 0.7,
      emissive: "#000000",
      emissiveIntensity: 0,
      texture: null,
      offsetX: -0.01,
      offsetY: 0,
    },
    backgroundColor: "#16A34A",
    textColor: "white",
  },
]
